python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run023 --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 5e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev_masked.json distant_supervision/data/BioNLP-ST_2013/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 6006 --overwrite_output_dir
python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run024 --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 5e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev_masked.json distant_supervision/data/BioNLP-ST_2013/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 7007 --overwrite_output_dir
python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run025 --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 5e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev_masked.json distant_supervision/data/BioNLP-ST_2013/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 8008 --overwrite_output_dir

python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2011/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2011/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run026 --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 5e-5 --direct_data distant_supervision/data/BioNLP-ST_2013/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2011/dev_masked.json distant_supervision/data/BioNLP-ST_2011/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 6006 --overwrite_output_dir
python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2011/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2011/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run027 --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 5e-5 --direct_data distant_supervision/data/BioNLP-ST_2013/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2011/dev_masked.json distant_supervision/data/BioNLP-ST_2011/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 7007 --overwrite_output_dir
python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2011/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2011/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run028 --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 5e-5 --direct_data distant_supervision/data/BioNLP-ST_2013/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2011/dev_masked.json distant_supervision/data/BioNLP-ST_2011/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 8008 --overwrite_output_dir

python -m distant_supervision.train_pedl --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2011/train_masked.hdf5 --dev distant_supervision/data/BioNLP-ST_2011/dev_masked.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/pedl --num_train_epoch 20 --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-STs/all_masked.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2011/dev_masked.json distant_supervision/data/BioNLP-ST_2011/test_masked.json --direct_weight 0.2  --max_bag_size 100 --seed 5005 --overwrite_output_dir

