app_name: pedl-rebuild_pubtator_index
app_tag: rebuild_pubtator_index

header: == ${hydra.help.app_name} ==

footer: |-
  You can find the detailed description on how to use
  PEDL here: https://github.com/leonweber/pedl

template: |-
  ${hydra.help.header}
  
  This is ${hydra.help.app_name}
  You can use ${hydra.help.app_name} as follows: 
  ${hydra.help.app_name} pubtator=[]
  
  == Flags == 
  
  required:
    local_pubtator  : the address to the local pubtator (e.g. localhost:9200). 
                      If empty string then no local pubtator is used [str] (default: "")
  optional:
    n_processes : number of processes for parallelization [int] (default: 1)

  -------
  ${hydra.help.footer}