# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_
  - database: default
  - entities: default
  - type: protein_protein
  - elastic: default
  - override hydra/help: rebuild_pubtator_index_help

pubtator_file: ???

n_processes: 1
